apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  USER_SERVICE_URL: "http://user-service:80"
  AUTH_SERVICE_URL: "http://auth-service:80"
  ORDER_SERVICE_URL: "http://order-service:80"
  PAYMENT_SERVICE_URL: "http://payment-service:80"