apiVersion: v2
name: payment-service
description: A service allowing users to pay for their orders using external APIs

type: application
version: 1.0.1
appVersion: "1.0.0"

dependencies:
  - name: common-chart
    version: "1.0.1"
    repository: "file://../common/common-chart"

  - name: mongodb
    version: "18.1.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"