apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: kafka
      protocol: TCP
      port: {{ .Values.ports.client }}
      targetPort: {{ .Values.ports.client }}
    - name: controller
      protocol: TCP
      port: {{ .Values.ports.internal }}
      targetPort: {{ .Values.ports.internal }}