apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: innowise-app-secret
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: innowise-app-secret
                  key: DB_PASSWORD
            - name: DB_ORDER_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: innowise-app-secret
                  key: DB_ORDER_SCHEMA
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://order-db:5432/$(DB_ORDER_SCHEMA)"
          envFrom:
            - configMapRef:
                name: order-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80