apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  KAFKA_BOOTSTRAP: "kafka-service:9092"
  USER_SERVICE_URL: "http://user-service:80"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://order-db:5432/$(DB_ORDER_SCHEMA)"