common-chart:
  replicaCount: 1

  image:
    repository: api-gateway
    tag: latest

  service:
    name: api-gateway

  env:
    - name: ACCESS_TOKEN_JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: innowise-app-secret
          key: ACCESS_TOKEN_JWT_SECRET
    - name: USER_SERVICE_URL
      value: http://user-service:80
    - name: AUTH_SERVICE_URL
      value: http://auth-service:80
    - name: ORDER_SERVICE_URL
      value: http://order-service:80
    - name: PAYMENT_SERVICE_URL
      value: http://payment-service:80