common-chart:
  replicaCount: 1

  image:
    repository: order-service
    tag: latest

  service:
    name: order-service

  env:
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: innowise-app-secret
          key: DB_USER
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: innowise-app-secret
          key: DB_PASSWORD
    - name: DB_ORDER_SCHEMA
      valueFrom:
        secretKeyRef:
          name: innowise-app-secret
          key: DB_ORDER_SCHEMA
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://order-db:5432/$(DB_ORDER_SCHEMA)
    - name: KAFKA_BOOTSTRAP
      value: kafka-service:9092
    - name: USER_SERVICE_URL
      value: http://user-service:80
