architecture: standalone

master:
  service:
    create: false
  persistence:
    enabled: true
    size: 100Mi

replica:
  replicaCount: 0

sentinel:
  enabled: false

auth:
  enabled: false

fullnameOverride: "user-redis"

service:
  type: ClusterIP
  ports:
    postgresql: 6379