apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db-deployment
  labels:
    app: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: innowise-app-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: innowise-app-secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: DB_USER_SCHEMA
                  name: innowise-app-secret

---
apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort