apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db-stateful-set
  labels:
    app: user-db
spec:
  replicas: 1
  serviceName: user-db
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: innowise-app-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: innowise-app-secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: DB_USER_SCHEMA
                  name: innowise-app-secret
          readinessProbe:
            exec:
              command: [ "pg_isready", "-q" ]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec psql -U "$POSTGRES_USER" -d postgres -c "SELECT 1"
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
  volumeClaimTemplates:
    - metadata:
        name: user-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432