replicaCount: 1

image:
  repository: auth-service
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80

probes:
  liveness:
    path: /actuator/health/liveness
    port: http
    initialDelaySeconds: 45
    periodSeconds: 5
    failureThreshold: 5
    timeoutSeconds: 2
  readiness:
    path: /actuator/health/readiness
    port: 80
    initialDelaySeconds: 45
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 2

database:
  host: auth-db
  port: 5432